// Generated by Prisma, do not modify manually
export interface DiscussionType {
  id: number;
  verse: string;
  date: Date;
  updatedAt: Date;
  comments: Comment[];
}

// Generated by Prisma, do not modify manually
export interface UserType {
  id: number;
  name: string;
  email: string;
  image: string;
  comments: Comment[];
  isAdmin: boolean;
}

// Generated by Prisma, do not modify manually
export interface CommentType {
  id: number;
  text: string;
  version: string;
  reactions: string[];
  reports: string[];
  upvotes: string[];
  downvotes: string[];
  author: UserType;
  authorId: number;
  discussion: DiscussionType;
  discussionId: number;
  parentCommentId: number | null;
  parentComment: Comment | null;
  replies: Comment[];
  createdAt: Date;
  updatedAt: Date;
}
